name: Run Privacy Modal Agree Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Chromium browser
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    - name: Launch browser and run Playwright test
      run: |
        npx playwright test --browser chromium PrivacyModalAgreeTest.js
    - name: Generate report with video
      run: |
        npx playwright show-trace test-results/*.trace.zip
        npx playwright show-video test-results/*.mp4
    - name: Save report to test-result folder
      run: |
        mkdir -p test-results
        mv *.zip *.mp4 test-results/
