name: NodeJS with Webpack Report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build with npm run build
      run: npm run build

    - name: Generate Webpack report
      run: npx webpack --profile --json > stats.json && npx webpack-bundle-analyzer stats.json --no-open --html test-results/report.html

    - name: Upload Webpack report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: webpack-report
        path: ./test-results
